# Generated by Django 5.0.6 on 2024-07-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student_class', '0002_student_class_delete_class'),
        ('teacher', '0002_remove_teacher_courses_taught_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='syllabus',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='semester',
            new_name='trimester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(related_name='courses', to='student_class.student_class'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='rita', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
