# Generated by Django 5.0.6 on 2024-07-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_rename_course_department_course_department_and_more'),
        ('student_class', '0002_student_class_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_date', models.TimeField()),
                ('day_of_week', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='course.course')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='student_class.student_class')),
            ],
        ),
    ]
