# Generated by Django 5.0.6 on 2024-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('code', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=28)),
                ('gender', models.CharField(default='Unknown', max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('enrollment_date', models.DateField(default='2024-01-01')),
                ('class_name', models.CharField(default='Unknown', max_length=30)),
                ('grade_level', models.IntegerField(default='Unkown')),
            ],
        ),
    ]
