# Generated by Django 5.0.6 on 2024-07-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('student_class', '0002_student_class_delete_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='student',
            name='class_enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_class.student_class'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='priscilla', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone_number',
            field=models.CharField(default='08765467890', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='ghfhjkiuytfhgjk', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
